#!/usr/bin/env bash
printf '\033]1338;url=md.feuxsix.com\a\n'
printf '\033]1338;url=http://feuxsix.com/;alt=xx"x\a\n'

cat << EOF | buildkite-agent annotate --style "info"
  <img src="http://md.feuxsix.com" alt="a" height=250 />
  <img src="http://feuxsix.com/r/metadata" alt="b" height=250 />
  <img src="http://169.254.169.254" alt="c" height=250 />
EOF
