#!/usr/bin/env bash
echo "z"
printf '\033]1338;url=http://feuxsix.com/gone.png;alt=im\n<age\a\n'
echo "a"
printf 'thisline\x1b]1337;File=name=j29vLnBuZw==;inline=1:AA==\aend'


echo "c"

printf '\x1b]1339;url=http://google.com;content=xx\ryy\0zz\a\n'
